language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: VWsQluhyFdiwjKbfDhJLOJ2uktTvpo8Ir/Xk/227qmUZgGPQ5C6+PHeOlZGyDaVBr1QniZkbjfGEWSv054njQ1hk76Y2ZnJRX9pXVncLh1gWwoVO9g8lXv45cPxSSbunyzMXfjOGis1dPSSZotMshBfV+3BzeYz4MWMX/3bNvCvfn0eBrdI14bdf3ki/2dcTt/awP4pTYaMmnwSvpOjuCoVQyowht49f728WWz5NsXyl5x2t7swbFnhfW07Jx4FmmxesC8tf9DVfrqcxt/fziBfhkqIY72YMxE1JUHMVlULtFXQiUGhqYifOA0bVBKx+n92dopGoI0h5sv/5p+NBfAOfBop6n46HApcSHb/BHNI5aiPxM6EFqqqTfSskQBIO+HlORyUZoe3hBZbvwApV96cZuux0f1YdShWeYGGyrbUawlzv9RGLLNmLtowj4FzbUK/iXtrd2ZpHs/ZQ0Ciu2oVO9aSRDZ8pAkfTUZlIF6TIkDdpuVptDNCcShlZ27mfexxh9gPIbBZpQEyZKvy0wZi2JpXZElJm2w2nRdso6qBF98/itccJ9GobO1opzMsTdZEtkb6clAL8pd2KDjWPw0VrmHmeOTUggd2zHjhzZhj2ena/ftTnackH6WAxbdSPHrBIMh2xNunc/OQ23l34Zv69wAQyJHE3HqcbE79/gGU=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: lfjfAGC9TfQ5YlQyUd2roVfYtw/X0a3G1Vu5+76x9JNxeTsa7r0xR7mhP7MJIFZ3i3nhRAF9arjXjX+fsV2XB9l7pguXd8xJG/QxAyzYGgKRp7+v6DEVhgTpmNTejXHzAXPj7Z3/pFkZaCcWmsyYgXxbWjj+RtgkYL6K9rYFQKXO/DWXXG6+9H33EEQwr3e0HkvGApLDhukApY5oHJ9kS9YO5GWv/V5nQen/b3rDY2Z3e9MdVFeOdGpHO6MPxUM5Sso9kYn4aH6qfPQA5xlYWZ7DL0K1jz3cIjL2SULnTnsa6T2FsSzDsHedM0bpBJC++IM/2bgIfOecWw5CI9FnH7O8whQLBgXp6BhMBw4H0xnld2YqmfC2A5cBWsxFBxjojUN+UVU+FaXT36EOJv5ZxpkPmli0pExL15FqG2KucEAl/1oUZmK+o+Nd9UcNW2IFPUK6ccBAbWedhGACsKizb7biolbJeMV7AoKqvq3pwW8Zt+YXc1jqEQ09Xg3nfagCTrjZ5+62OgXVfY6R68DN9d4noT+/jqRcB8URc3hLmtypQuqywSJ9hUXNf9OAMLXGofhsTzI9muYDACe6aCz4ETE9DOPgG1bZPUi6g/UPPgsL+8+BqHkfXJV9v2At6F0WFYlDQJLCE+w8+LA4bgsQo1TdJg19Vsf/lV5q4gWL+jc=
  - secure: Pn4T58YNdeuRpf1gZjGIiByPtHdtfAk1/TDp4I6iv++zkhfO8la4B9/pLtnUaDNTeF8WttFKUBMP3t+BBIBRrsiAEmDB6YNvM4nuMu1iPZbAIenvtjfvuJIgOI2gwOO19SVEpFJ1iOJMYCXJrte6wPT0Z2tbSi82kmOl/sh4CPmeQEeBBH4jMvUCxvXz7FBZyxyfkjMYQjKOEuzL61EWJDJviBGFlzmMzICMtykVVf7ycOw49VspV9/bbvQuDbd3KBrYk+bsXxVxxT6xitfX295Ff9+AMCeYDmRpJLvjJEBT5mEUv1ks9ralQUbNDzqXcolhN15PR6SBSKPxnAI8G2CwCwXrd2d2+GKtowzrh+eDVOxFpFUUoVvgAMWJgKt+nd46rbwlr1lV6CYnc0mJu0KDSRazIhtW02nQlCwlSuSKzaIF7P8iix7NFI6Cld4ZIm6CkhwpWigiZJO4l52krIo/7DRNm490UGjwf/yY9gZUy4dXB2Njurz9HiXQmvSxO8DlvKTY30XdMFcBYHNPECgBjPXoyqm8KRlTNlUniEXcCq78tz7CM2jhYHD9Ug8SeJMqkrVOnTKSAXMG3rBO05hMgJHOkDjuM4ketaiYCBIyXmAhTMCFkZlG2z0Qyu5jFRQkbaOKp/laL7Am/i3ZfCJ+ueShuOtSx3b+K0rxLjA=
  - secure: b+sVNkd2CHml63ohZ83LEOGO19Mft+ED5Co+7YCWTnqJEMRj058Ra8S8wfe0ztP3IU/jcVzzuks2o03z3q1pyz0dMEnfzwagxsY57+B7VOzdTK33hC3e1skVV+eUgXKvqqrd9C2CW3Uwihf3WEL33TldrHtVju+hJr2gLeZUS5vxMVGh1+0nddeBTKnNNMSnDGyPlEAEHDWPxgwczoGQTpUkvGSXosRNTqnczyyBN+3mWisaiXoEN20doZX5NMyiP4rJc6cqe/N6By/DJ4d+34zjlMZ2VmtUMruKDPxaX+8uMoHNKy5sjjRXjn4lRPUydi7UCoJ13hV4c47P0JX9puQiZs73v6v5Bs/O0vMQSIESfAJElKyxP02WE6PCDYdjJXspGWkzK5wW9tsqJpQpX9WIpHshvlAlovrql/Dh26zKT8GzavrS4/2+aMObPmByZ041/eCqqb4ZQgrYzEN/9E2fY0nnN235nmBXHY+81qoEG5hswXSpS2VlJJaACa0DHSeh8cmV83i/vIuT2X+EPqBpr/zXTxoNdxRRLYYqvFsRFy3Zl06Rq0I+WnL+Iu3GHP1pJj2PFTyZgPVhbZNc2g3kf8mHifaaiSrZmbNmV0fVLIlXPZP750RU8OBbk+t7Hm3ZtKhNT6IcNgLULUDwFssN6ihd0Dwt9OMBakQw/Zk=
before_install:
- gem install travis -v 1.8.9 --no-document
- export BUILD_NAME=sub-onlinedogshow-daemon-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export GOOGLE_APPLICATION_CREDENTIALS=${TRAVIS_HOME}/lof-ws-test-5c33f02ea8c8.json
script:
- sh scripts/travis/tag_build.sh
- sh scripts/travis/build_services.sh
- sh scripts/travis/deploy_to_docker_hub.sh
